# Generated by Django 6.1 on 2026-08-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ['-criado_em']},
        ),
    ]
